# Generated by Django 4.0.4 on 2022-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(blank=True, max_length=50, null=True)),
                ('university_enrollment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('nimcet_cet_rank', models.CharField(blank=True, max_length=10, null=True)),
                ('class_batch', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_date', models.DateTimeField(auto_now=True)),
                ('total_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_deposited_at_university', models.CharField(blank=True, max_length=50, null=True)),
                ('collected_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('Balance_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_of_payment', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('instrument_no', models.CharField(blank=True, max_length=50, null=True)),
                ('drawn_on_bank_name', models.CharField(default=False, max_length=50)),
                ('transaction_date_of_ch_dd', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_date_in_bank', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('mob_no', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
