# Generated by Django 4.0.4 on 2022-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesm', '0002_alter_fee_balance_fee_alter_fee_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='credit_date_in_bank',
        ),
        migrations.AlterField(
            model_name='fee',
            name='Balance_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='collected_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='drawn_on_bank_name',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_deposited_at_university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='instrument_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='mode_of_payment',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='name_of_student',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='transaction_date_of_ch_dd',
            field=models.DateTimeField(blank=True, help_text='DD/MM/YYYY'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='university_enrollment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
