# Generated by Django 4.0.4 on 2022-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesm', '0003_remove_fee_credit_date_in_bank_alter_fee_balance_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='transaction_date_of_ch_dd',
        ),
        migrations.AlterField(
            model_name='fee',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
