# Generated by Django 4.0.4 on 2022-05-19 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feesm', '0006_fee_security_fee_fee_student_activity_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='deposit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 19, 19, 46, 24, 613945, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
